url="http://monitor.cs.umbc.edu/suid/"

setuid = 1 << 0
setgid = 1 << 1
rules = {"/usr/libexec/utempter/utempter": setgid,
	"/bin/umount": setuid,
	"/usr/libexec/pt_chown": setuid,
	"/usr/libexec/openssh/ssh-keysign": setuid,
	"/usr/bin/chage": setuid,
	"/usr/bin/ksu": setuid,
	"/usr/sbin/ping6": setuid,
	"/bin/fusermount": setuid,
	"/lib64/dbus-1/dbus-daemon-launch-helper": setuid,
	"/usr/bin/ssh-agent": setgid,
	"/usr/bin/write": setgid,
	"/usr/bin/fusermount": setuid,
	"/usr/bin/passwd": setuid,
	"/usr/lib64/nspluginwrapper/plugin-config": setuid,
	"/usr/bin/atrm": setuid,
	"/usr/libexec/polkit-1/polkit-agent-helper-1": setuid,
	"/usr/bin/locate": setgid,
	"/bin/su": setuid,
	"/usr/bin/chfn": setuid,
	"/usr/sbin/postdrop": setgid,
	"/usr/sbin/usernetctl": setuid,
	"/bin/ping6": setuid,
	"/usr/bin/pkexec": setuid,
	"/sbin/umount.nfs": setuid,
	"/sbin/unix_chkpwd": setuid,
	"/usr/sbin/postqueue": setgid,
	"/bin/ping": setuid,
	"/sbin/umount.nfs4": setuid,
	"/usr/libexec/pulse/proximity-helper": setuid,
	"/usr/bin/sudoedit": setuid,
	"/usr/bin/sg": setuid,
	"/bin/mount": setuid,
	"/usr/bin/atq": setuid,
	"/sbin/netreport": setgid,
	"/sbin/mount.nfs": setuid,
	"/usr/bin/Xorg": setuid,
	"/usr/bin/wall": setgid,
	"/usr/bin/sudo": setuid,
	"/usr/bin/newgrp": setuid,
	"/usr/bin/staprun": setuid,
	"/usr/lib64/vte/gnome-pty-helper": setgid,
	"/usr/sbin/lockdev": setgid,
	"/usr/sbin/suexec": setuid,
	"/sbin/mount.nfs4": setuid,
	"/usr/libexec/abrt-action-install-debuginfo-to-abrt-cache": setuid,
	"/usr/bin/X": setuid,
	"/sbin/pam_timestamp_check": setuid,
	"/usr/bin/gpasswd": setuid,
	"/usr/bin/crontab": setuid,
	"/usr/bin/at": setuid,
	"/usr/sbin/userhelper": setuid,
	"/usr/bin/chsh": setuid,
	}
